#!/bin/sh

RELATIVE_PATH="`dirname \"$0\"`"
PROJECT_PATH=$(realpath $RELATIVE_PATH/..)
SCRIPT_DIR="$PROJECT_PATH/script"

cd $PROJECT_PATH

DATA_NAME="$1"
DATA_FILE_NAME="$DATA_NAME.dat"
DATA_FILE_PATH="$PROJECT_PATH/results/$DATA_FILE_NAME"

if ! [ -e $DATA_FILE_PATH ]
then
    echo "file '$DATA_FILE_PATH' does not exist"
    exit 1
fi


OUTPUT_DIR="/tmp/ttt"
TTT_SCRIPT="tttplots.pl"

mkdir -p $OUTPUT_DIR
cp "$PROJECT_PATH/$TTT_SCRIPT" $OUTPUT_DIR
cp $DATA_FILE_PATH $OUTPUT_DIR
cd $OUTPUT_DIR
# rm *

./$TTT_SCRIPT -f $DATA_NAME
for PS_FILE in `ls *.ps`
do
    PDF_FILE="${PS_FILE%.*}.pdf"
    ps2pdf $PS_FILE
done

mkdir -p $PROJECT_PATH/graph
mv *.pdf $PROJECT_PATH/graph/
rm -rf * $OUTPUT_DIR
