#!/bin/sh

RELATIVE_PATH="`dirname \"$0\"`"
PROJECT_PATH=$(realpath $RELATIVE_PATH/..)
SCRIPT_DIR="$PROJECT_PATH/script"

cd $PROJECT_PATH

TTT_RESULTS_DIR="$PROJECT_PATH/TTT_results"
TTT_RESULTS_LIST=`ls $TTT_RESULTS_DIR/*.dat`
GRAPHS_DIR="$PROJECT_PATH/report/figure/ttt_plot"

for RESULT_FILE_PATH in $TTT_RESULTS_LIST
do
    echo "Processing $RESULT_FILE_PATH"
    RESULT_FILE_NAME=`basename $RESULT_FILE_PATH`
    DATA_NAME="${RESULT_FILE_NAME%.*}"
    DATA_FILE_NAME="$DATA_NAME.dat"
    DATA_FILE_PATH="$TTT_RESULTS_DIR/$DATA_FILE_NAME"

    if ! [ -e $DATA_FILE_PATH ]
    then
        echo "file '$DATA_FILE_PATH' does not exist"
        exit 1
    fi

    OUTPUT_DIR="/tmp/ttt"
    TTT_SCRIPT="tttplots.pl"

    mkdir -p $OUTPUT_DIR
    cp "$PROJECT_PATH/$TTT_SCRIPT" $OUTPUT_DIR
    cp $DATA_FILE_PATH $OUTPUT_DIR
    cd $OUTPUT_DIR

    ./$TTT_SCRIPT -f $DATA_NAME
    # for PS_FILE in `ls *.ps`
    # do
    #     PDF_FILE="${PS_FILE%.*}.pdf"
    #     ps2pdf $PS_FILE
    # done

    mkdir -p $GRAPHS_DIR
    mv *.jpeg $GRAPHS_DIR
    cd /tmp
    rm -rf $OUTPUT_DIR

done
