#!/bin/sh

RELATIVE_PATH="`dirname \"$0\"`"
PROJECT_PATH=$(realpath $RELATIVE_PATH/..)
SCRIPT_DIR="$PROJECT_PATH/script"

cd $PROJECT_PATH
PROBLEM_INSTANCE=`realpath $2`

gradle $1:run --args="$PROBLEM_INSTANCE" | tee run.log
