#!/bin/sh

RELATIVE_PATH="`dirname \"$0\"`"
PROJECT_PATH=$(realpath $RELATIVE_PATH/..)
SCRIPT_DIR="$PROJECT_PATH/script"

KQBF="KQBF"
KQBF_GRASP="KQBF_GRASP"


if [[ $# -ne 1 ]] || [[ $1 != $KQBF ]] && [[ $1 != $KQBF_GRASP ]]
then
    echo "usage: $0 ALGORITHM"
    echo "currently available algorithms: $KQBF, $KQBF_GRASP"
    exit
fi

gradle $1:run | tee ${PROJECT_PATH}/run.log
