#!/bin/sh

RELATIVE_PATH="`dirname \"$0\"`"
PROJECT_PATH=$(realpath $RELATIVE_PATH/..)
SCRIPT_DIR="$PROJECT_PATH/script"

cd $PROJECT_PATH

exists_in_list ()
{
    # $1: list to check against
    # $2: value to be checked
    for __VALUE in $1
    do
        if [ $2 = $__VALUE ]
        then
            return 0
        fi
    done
    return 1
}

DEFAULT_PROJECT="kqbf"
PROJECTS_LIST="$DEFAULT_PROJECT qbf ttt"
PROJECT="$1"

if ! [ $PROJECT ]
then
    PROJECT=$DEFAULT_PROJECT
    echo "input arg is invalid: $1"
    echo "setting project as '$DEFAULT_PROJECT'"
fi

if ! exists_in_list "$PROJECTS_LIST" "$PROJECT"
then
    echo "arg '$PROJECT' is invalid"
    echo "valid projects: $PROJECTS_LIST"
    exit 1
fi

gradle $PROJECT:run | tee ${PROJECT_PATH}/$PROJECT.log

